from teams import Teams


class Teamlist:
    # and add them to a list
    teams = []
    
    # create a team for all listed countries

    # add the team to the list
    teams.append(Teams(50, 'Afghanistan', 'AFG'))
    teams.append(Teams(80, 'Australia', 'AUS'))
    teams.append(Teams(0, 'Bahrain', 'BHR'))
    teams.append(Teams(0, 'Bangladesh', 'BAN'))
    teams.append(Teams(0, 'Bhutan', 'BHU'))
    teams.append(Teams(0, 'Brunei Darussalam', 'BRU'))
    teams.append(Teams(0, 'Cambodia', 'CAM'))
    teams.append(Teams(0, 'China PR', 'CHN'))
    teams.append(Teams(0, 'Chinese Taipei', 'TPE'))
    teams.append(Teams(0, 'Guam', 'GUM'))
    teams.append(Teams(0, 'Hong Kong', 'HKG'))
    teams.append(Teams(0, 'India', 'IND'))
    teams.append(Teams(0, 'Indonesia', 'INA'))
    teams.append(Teams(0, 'IR Iran', 'IRI'))
    teams.append(Teams(0, 'Iraq', 'IRQ'))
    teams.append(Teams(0, 'Japan', 'JPN'))
    teams.append(Teams(0, 'Jordan', 'JOR'))
    teams.append(Teams(0, 'Korea DPR', 'PRK'))
    teams.append(Teams(0, 'Korea Republic', 'KOR'))
    teams.append(Teams(0, 'Kuwait', 'KUW'))
    teams.append(Teams(0, 'Kyrgyz Republic', 'KGZ'))
    teams.append(Teams(0, 'Laos', 'LAO'))
    teams.append(Teams(0, 'Lebanon', 'LIB'))
    teams.append(Teams(0, 'Macau', 'MAC'))
    teams.append(Teams(0, 'Malaysia', 'MAS'))
    teams.append(Teams(0, 'Maldives', 'MDV'))
    teams.append(Teams(0, 'Mongolia', 'MGL'))
    teams.append(Teams(0, 'Myanmar', 'MYA'))
    teams.append(Teams(0, 'Nepal', 'NEP'))
    teams.append(Teams(0, 'Northern Mariana Islands', 'NMI'))
    teams.append(Teams(0, 'Oman', 'OMA'))
    teams.append(Teams(0, 'Pakistan', 'PAK'))
    teams.append(Teams(0, 'Palestine', 'PLE'))
    teams.append(Teams(0, 'Philippines', 'PHI'))
    teams.append(Teams(0, 'Qatar', 'QAT'))
    teams.append(Teams(0, 'Saudi Arabia', 'KSA'))
    teams.append(Teams(0, 'Singapore', 'SIN'))
    teams.append(Teams(0, 'Sri Lanka', 'SRI'))
    teams.append(Teams(0, 'Syria', 'SYR'))
    teams.append(Teams(0, 'Tajikistan', 'TJK'))
    teams.append(Teams(0, 'Thailand', 'THA'))
    teams.append(Teams(0, 'Timor-Leste', 'TLS'))
    teams.append(Teams(0, 'Turkmenistan', 'TKM'))
    teams.append(Teams(0, 'United Arab Emirates', 'UAE'))
    teams.append(Teams(0, 'Uzbekistan', 'UZB'))
    teams.append(Teams(0, 'Vietnam', 'VIE'))
    teams.append(Teams(0, 'Yemen', 'YEM'))

    #change to rating a random number between 1 and 100
   



    # create a team for all listed countries

    # add the team to the list
    teams.append(Teams(0, 'Anguilla', 'AIA'))
    teams.append(Teams(0, 'Antigua and Barbuda', 'ATG'))
    teams.append(Teams(0, 'Aruba', 'ARU'))
    teams.append(Teams(0, 'Bahamas', 'BAH'))
    teams.append(Teams(0, 'Barbados', 'BRB'))
    teams.append(Teams(0, 'Belize', 'BIZ'))
    teams.append(Teams(0, 'Bermuda', 'BER'))
    teams.append(Teams(0, 'Bonaire', 'BON'))
    teams.append(Teams(0, 'British Virgin Islands', 'IVB'))
    teams.append(Teams(0, 'Canada', 'CAN'))
    teams.append(Teams(0, 'Cayman Islands', 'CAY'))
    teams.append(Teams(0, 'Costa Rica', 'CRC'))
    teams.append(Teams(0, 'Cuba', 'CUB'))
    teams.append(Teams(0, 'Curaçao', 'CUW'))
    teams.append(Teams(0, 'Dominica', 'DMA'))
    teams.append(Teams(0, 'Dominican Republic', 'DOM'))
    teams.append(Teams(0, 'El Salvador', 'ESA'))
    teams.append(Teams(0, 'French Guiana', 'GUF'))
    teams.append(Teams(0, 'Grenada', 'GRN'))
    teams.append(Teams(0, 'Guadeloupe', 'GLP'))
    teams.append(Teams(0, 'Guatemala', 'GUA'))
    teams.append(Teams(0, 'Guyana', 'GUY'))
    teams.append(Teams(0, 'Haiti', 'HAI'))
    teams.append(Teams(0, 'Honduras', 'HON'))
    teams.append(Teams(0, 'Jamaica', 'JAM'))
    teams.append(Teams(0, 'Martinique', 'MTQ'))
    teams.append(Teams(0, 'Mexico', 'MEX'))
    teams.append(Teams(0, 'Montserrat', 'MSR'))
    teams.append(Teams(0, 'Nicaragua', 'NCA'))
    teams.append(Teams(0, 'Panama', 'PAN'))
    teams.append(Teams(0, 'Puerto Rico', 'PUR'))
    teams.append(Teams(0, 'Saint Kitts and Nevis', 'SKN'))
    teams.append(Teams(0, 'Saint Lucia', 'LCA'))
    teams.append(Teams(0, 'Saint Martin', 'MAF'))
    teams.append(Teams(0, 'Saint Vincent and the Grenadines', 'VIN'))
    teams.append(Teams(0, 'Sint Maarten', 'SMA'))
    teams.append(Teams(0, 'Suriname', 'SUR'))
    teams.append(Teams(0, 'Trinidad and Tobago', 'TRI'))
    teams.append(Teams(0, 'Turks and Caicos Islands', 'TCA'))
    teams.append(Teams(0, 'United States', 'USA'))
    teams.append(Teams(0, 'US Virgin Islands', 'ISV'))

    # create a team for all listed countries

    # add the team to the list
    teams.append(Teams(0, 'Argentina', 'ARG'))
    teams.append(Teams(0, 'Bolivia', 'BOL'))
    teams.append(Teams(0, 'Brazil', 'BRA'))
    teams.append(Teams(0, 'Chile', 'CHI'))
    teams.append(Teams(0, 'Colombia', 'COL'))
    teams.append(Teams(0, 'Ecuador', 'ECU'))
    teams.append(Teams(0, 'Paraguay', 'PAR'))
    teams.append(Teams(0, 'Peru', 'PER'))
    teams.append(Teams(0, 'Uruguay', 'URU'))
    teams.append(Teams(0, 'Venezuela', 'VEN'))

    # create a team for all listed countries

    # add the team to the list
    teams.append(Teams(0, 'American Samoa', 'ASA'))
    teams.append(Teams(0, 'Cook Islands', 'COK'))
    teams.append(Teams(0, 'Fiji', 'FIJ'))
    teams.append(Teams(0, 'Kiribati', 'KIR'))
    teams.append(Teams(0, 'New Caledonia', 'NCL'))
    teams.append(Teams(0, 'New Zealand', 'NZL'))
    teams.append(Teams(0, 'Niue', 'NIU'))
    teams.append(Teams(0, 'Papua New Guinea', 'PNG'))
    teams.append(Teams(0, 'Samoa', 'SAM'))
    teams.append(Teams(0, 'Solomon Islands', 'SOL'))
    teams.append(Teams(0, 'Tahiti', 'TAH'))
    teams.append(Teams(0, 'Tonga', 'TGA'))
    teams.append(Teams(0, 'Tuvalu', 'TUV'))
    teams.append(Teams(0, 'Vanuatu', 'VAN'))

    # create a team for all listed countries

    # add the team to the list
    teams.append(Teams(0, 'Albania', 'ALB'))
    teams.append(Teams(0, 'Andorra', 'AND'))
    teams.append(Teams(0, 'Armenia', 'ARM'))
    teams.append(Teams(0, 'Austria', 'AUT'))
    teams.append(Teams(0, 'Azerbaijan', 'AZE'))
    teams.append(Teams(0, 'Belarus', 'BLR'))
    teams.append(Teams(0, 'Belgium', 'BEL'))
    teams.append(Teams(0, 'Bosnia and Herzegovina', 'BIH'))
    teams.append(Teams(0, 'Bulgaria', 'BUL'))
    teams.append(Teams(0, 'Croatia', 'CRO'))
    teams.append(Teams(0, 'Cyprus', 'CYP'))
    teams.append(Teams(0, 'Czech Republic', 'CZE'))
    teams.append(Teams(0, 'Denmark', 'DEN'))
    teams.append(Teams(0, 'England', 'ENG'))
    teams.append(Teams(0, 'Estonia', 'EST'))
    teams.append(Teams(0, 'Faroe Islands', 'FRO'))
    teams.append(Teams(0, 'Finland', 'FIN'))
    teams.append(Teams(0, 'France', 'FRA'))
    teams.append(Teams(0, 'Georgia', 'GEO'))
    teams.append(Teams(0, 'Germany', 'GER'))
    teams.append(Teams(0, 'Gibraltar', 'GIB'))
    teams.append(Teams(0, 'Greece', 'GRE'))
    teams.append(Teams(0, 'Hungary', 'HUN'))
    teams.append(Teams(0, 'Iceland', 'ISL'))
    teams.append(Teams(0, 'Israel', 'ISR'))
    teams.append(Teams(0, 'Italy', 'ITA'))
    teams.append(Teams(0, 'Kazakhstan', 'KAZ'))
    teams.append(Teams(0, 'Kosovo', 'KOS'))
    teams.append(Teams(0, 'Latvia', 'LAT'))
    teams.append(Teams(0, 'Liechtenstein', 'LIE'))
    teams.append(Teams(0, 'Lithuania', 'LTU'))
    teams.append(Teams(0, 'Luxembourg', 'LUX'))
    teams.append(Teams(0, 'Malta', 'MLT'))
    teams.append(Teams(0, 'Moldova', 'MDA'))
    teams.append(Teams(0, 'Montenegro', 'MNE'))
    teams.append(Teams(0, 'Netherlands', 'NED'))
    teams.append(Teams(0, 'North Macedonia', 'MKD'))
    teams.append(Teams(0, 'Northern Ireland', 'NIR'))
    teams.append(Teams(0, 'Norway', 'NOR'))
    teams.append(Teams(0, 'Poland', 'POL'))
    teams.append(Teams(0, 'Portugal', 'POR'))
    teams.append(Teams(0, 'Republic of Ireland', 'IRL'))
    teams.append(Teams(0, 'Romania', 'ROU'))
    teams.append(Teams(0, 'Russia', 'RUS'))
    teams.append(Teams(0, 'San Marino', 'SMR'))
    teams.append(Teams(0, 'Scotland', 'SCO'))
    teams.append(Teams(0, 'Serbia', 'SRB'))
    teams.append(Teams(0, 'Slovakia', 'SVK'))
    teams.append(Teams(0, 'Slovenia', 'SVN'))
    teams.append(Teams(0, 'Spain', 'ESP'))
    teams.append(Teams(0, 'Sweden', 'SWE'))
    teams.append(Teams(0, 'Switzerland', 'SUI'))
    teams.append(Teams(0, 'Türkiye', 'TUR'))
    teams.append(Teams(0, 'Ukraine', 'UKR'))
    teams.append(Teams(0, 'Wales', 'WAL'))

    
    # create a team for all listed countries

    # add the team to the list
    teams.append(Teams(0, 'Algiers', 'ALG'))
    teams.append(Teams(0, 'Angola', 'ANG'))
    teams.append(Teams(0, 'Benin', 'BEN'))
    teams.append(Teams(0, 'Botswana', 'BOT'))
    teams.append(Teams(0, 'Burkina Faso', 'BUR'))
    teams.append(Teams(0, 'Burundi', 'BDI'))
    teams.append(Teams(0, 'Cameroon', 'CMR'))
    teams.append(Teams(0, 'Cape Verde', 'CPV'))
    teams.append(Teams(0, 'Central African Republic', 'CAF'))
    teams.append(Teams(0, 'Chad', 'CHA'))
    teams.append(Teams(0, 'Comoros', 'COM'))
    teams.append(Teams(0, 'Congo', 'CGO'))
    teams.append(Teams(0, 'Congo DR', 'COD'))
    teams.append(Teams(0, 'Côte d\'Ivoire', 'CIV'))
    teams.append(Teams(0, 'Djibouti', 'DJI'))
    teams.append(Teams(0, 'Egypt', 'EGY'))
    teams.append(Teams(0, 'Equatorial Guinea', 'GNQ'))
    teams.append(Teams(0, 'Eritrea', 'ERI'))
    teams.append(Teams(0, 'Eswatini', 'SWZ'))
    teams.append(Teams(0, 'Ethiopia', 'ETH'))
    teams.append(Teams(0, 'Gabon', 'GAB'))
    teams.append(Teams(0, 'Gambia', 'GAM'))
    teams.append(Teams(0, 'Ghana', 'GHA'))
    teams.append(Teams(0, 'Guinea', 'GUI'))
    teams.append(Teams(0, 'Guinea-Bissau', 'GBS'))
    teams.append(Teams(0, 'Kenya', 'KEN'))
    teams.append(Teams(0, 'Lesotho', 'LES'))
    teams.append(Teams(0, 'Liberia', 'LBR'))
    teams.append(Teams(0, 'Libya', 'LBY'))
    teams.append(Teams(0, 'Madagascar', 'MAD'))
    teams.append(Teams(0, 'Malawi', 'MAW'))
    teams.append(Teams(0, 'Mali', 'MLI'))
    teams.append(Teams(0, 'Mauritania', 'MTN'))
    teams.append(Teams(0, 'Mauritius', 'MRI'))
    teams.append(Teams(0, 'Morocco', 'MAR'))
    teams.append(Teams(0, 'Mozambique', 'MOZ'))
    teams.append(Teams(0, 'Namibia', 'NAM'))
    teams.append(Teams(0, 'Niger', 'NIG'))
    teams.append(Teams(0, 'Nigeria', 'NGA'))
    teams.append(Teams(0, 'Réunion', 'REU'))
    teams.append(Teams(0, 'Rwanda', 'RWA'))
    teams.append(Teams(0, 'São Tomé and Príncipe', 'STP'))
    teams.append(Teams(0, 'Senegal', 'SEN'))
    teams.append(Teams(0, 'Seychelles', 'SEY'))
    teams.append(Teams(0, 'Sierra Leone', 'SLE'))
    teams.append(Teams(0, 'Somalia', 'SOM'))
    teams.append(Teams(0, 'South Africa', 'RSA'))
    teams.append(Teams(0, 'South Sudan', 'SSD'))
    teams.append(Teams(0, 'Sudan', 'SUD'))
    teams.append(Teams(0, 'Tanzania', 'TAN'))
    teams.append(Teams(0, 'Togo', 'TOG'))
    teams.append(Teams(0, 'Tunisia', 'TUN'))
    teams.append(Teams(0, 'Uganda', 'UGA'))
    teams.append(Teams(0, 'Zambia', 'ZAM'))
    teams.append(Teams(0, 'Zanzibar', 'ZAN'))
    teams.append(Teams(0, 'Zimbabwe', 'ZIM'))